destination: ./_site
auto: true
lsi: false
server_port: 4000
pygments: true
markdown: rdiscount
permalink: date
favicon: /assets/img/favicon.png
rdiscount:
  extensions: [smart]
projects:
  database:
    name: Database
    git: https://github.com/opis/database
    version: 2.0.0
  closure:
    name: Closure
    git: https://github.com/opis/closure
    version: 1.3.0
  container:
    name: Container
    git: https://github.com/opis/container
    version: 2.2.0
  cache:
    name: Cache
    git: https://github.com/opis/cache
    version: 2.0.0
  session:
    name: Session
    git: https://github.com/opis/session
    version: 2.3.0
    